---
# Dovecot Installation and Configuration

- name: Install Dovecot packages
  apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-pgsql
    state: present

- name: Create vmail user
  user:
    name: vmail
    uid: 5000
    group: vmail
    home: /var/vmail
    shell: /usr/sbin/nologin
    system: yes
    create_home: yes

- name: Create vmail group
  group:
    name: vmail
    gid: 5000
    system: yes

- name: Set vmail directory permissions
  file:
    path: /var/vmail
    owner: vmail
    group: vmail
    mode: '0770'
    state: directory

- name: Configure Dovecot main config
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dovecot

- name: Configure Dovecot SQL
  template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: root
    group: dovecot
    mode: '0640'
  notify: restart dovecot

- name: Create Dovecot log files
  file:
    path: "{{ item }}"
    state: touch
    owner: dovecot
    group: adm
    mode: '0640'
  loop:
    - /var/log/dovecot.log
    - /var/log/dovecot-info.log
    - /var/log/dovecot-debug.log

- name: Ensure Dovecot is enabled and started
  systemd:
    name: dovecot
    enabled: yes
    state: started
