---
# Postfix Installation and Configuration

- name: Install Postfix and dependencies
  apt:
    name:
      - postfix
      - postfix-pgsql
      - libsasl2-modules
    state: present

- name: Stop Postfix before configuration
  systemd:
    name: postfix
    state: stopped

- name: Configure Postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: restart postfix

- name: Configure Postfix master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'
  notify: restart postfix

- name: Create PostgreSQL query files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: postfix
    mode: '0640'
  loop:
    - { src: 'pgsql-virtual-mailbox-domains.cf.j2', dest: '/etc/postfix/pgsql-virtual-mailbox-domains.cf' }
    - { src: 'pgsql-virtual-mailbox-maps.cf.j2', dest: '/etc/postfix/pgsql-virtual-mailbox-maps.cf' }
    - { src: 'pgsql-virtual-alias-maps.cf.j2', dest: '/etc/postfix/pgsql-virtual-alias-maps.cf' }
  notify: restart postfix

- name: Create Postfix log file
  file:
    path: /var/log/postfix.log
    state: touch
    owner: syslog
    group: adm
    mode: '0640'

- name: Ensure Postfix is enabled and started
  systemd:
    name: postfix
    enabled: yes
    state: started
